# Start and end years for era5 download, preprocessing and analysis
start = 1979
end = 2018

data_dir = '../data/'

[ERA5]
dir_base = '/home/lunet/gylc4/geodata/ERA5/'

[MIDAS]
dir_base = '../data/MIDAS/'
hourly_filename = 'midas_1979-2018_precip_select.zarr'

[plots]
